game/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'game'

urlpatterns = [
    url(r'^leaderboard/(?P<quiz_id>.+)/$', views.quiz_leaderboard, name='quiz_leaderboard'),
    url(r'^profile/$', views.profile, name='profile')
]

quizzie/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from game.views import index


urlpatterns = [
    url(r'^$', index, name='homepage'),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
]

game/models.py
import json
import uuid
import datetime
from django.db import models
from django.conf import settings
from channels import Group

from quizzie.settings import MSG_TYPE_MESSAGE


class Room(models.Model):
    title = models.CharField(max_length=255)
    staff_only = models.BooleanField(default=False)
    chat_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def websocket_group(self):
        """
        Returns the Channels Group that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return Group("room-%s" % self.id)

    def send_message(self, message, user, msg_type=MSG_TYPE_MESSAGE):
        """
        Called to send a message to the room on behalf of a user.
        """
        final_msg = {'room': str(self.id), 'message': message, 'username': user.username, 'msg_type': msg_type}

        # Send out the message to everyone in the room
        self.websocket_group.send(
            {"text": json.dumps(final_msg)}
        )


class Quiz(models.Model):
    name = models.CharField(max_length=64, verbose_name='Name of exam')
    id = models.CharField(unique=True, default=uuid.uuid4,
                          editable=False, max_length=50, primary_key=True)
    slug = models.SlugField(max_length=64, unique=True)
    room = models.OneToOneField(Room, null=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    id = models.CharField(unique=True, default=uuid.uuid4,
                          editable=False, max_length=50, primary_key=True)
    question_text = models.CharField(max_length=128, verbose_name='Enter question here.')
    is_final = models.BooleanField(default=False)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.question_text

    def get_options(self):
        return Option.objects.filter(question=self)


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    text = models.CharField(max_length=128, verbose_name='Answer\'s text here.')
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Response(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    selected_option = models.ForeignKey(Option, on_delete=models.CASCADE, null=True)
    is_correct = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.user.username + ' : ' + self.question.question_text + ' : ' + self.selected_option.text


class Score(models.Model):
    id = models.CharField(unique=True, default=uuid.uuid4,
                          editable=False, max_length=50, primary_key=True)
    date = models.DateTimeField(default=datetime.datetime.now())
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    quiz = models.ForeignKey(Quiz)
    max_score = models.IntegerField(blank=True, null=True)
    score = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.user.username + ' : ' + str(self.date) + ' : ' + str(self.score)

    def get_quiz(self):
        return self.quiz

    def get_score(self):
        return self.score

    def get_max_score(self):
        return self.max_score

    def get_quiz_id(self):
        return self.quiz.id

game/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Room, Quiz, Score, Room, Question
from django.contrib.auth.models import User
from django.http import JsonResponse



@login_required
def index(request):
    rooms = Room.objects.order_by("title")

    # Render that in the index template
    return render(request, "index.html", {
        "rooms": rooms,
    })


def quiz_leaderboard(request, quiz_id):
    quiz = Quiz.objects.get(id=quiz_id)
    scores = Score.objects.filter(quiz=quiz).order_by("score")
    questions = Question.objects.filter(quiz=quiz)
    print(questions)
    return render(request, "quiz/quiz_leaderboard.html", {
        "quiz_id": quiz_id,
        "quiz_name": quiz.name,
        "questions": questions,
        "scores": reversed(scores),
    })


def profile(request):
    if request.user.is_authenticated():
        username = request.user.username
        # print('user mila\nsadasds\ndfsdfds\n')
        user = User.objects.get(username=username)
        # print(user)
        scores = Score.objects.filter(user=user)

        return render(request, "profile.html", {
            # "quizzes": quizzes,
            "scores": scores,
        })
    else:
        data = {'Error': '404: Not Found'}
    return JsonResponse(data)

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/main.css" %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid flt">
        {% if user.is_authenticated %}

        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-line" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/quiz/profile"> Profile </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
        {% else %}
            <h1 class="welcome">Welcome to quizze!!</h1>
        {% endif %}
        </div>
    </nav>
    {% if user.is_authenticated %}
     &nbsp;<h2>Hello, <a class="nav-link" href="#">{{ user }}</a></h2>
    {% endif %}
    <div class="container mybg">
        {% block content %}
        {% endblock %}

    </div>
    {% block extra_body %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Quiz Home{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="mybg">
        <span style="font-size: xx-large">Avaliable Quizes:</span>
    <ol type="1" class="rooms">
        {% for room in rooms %}
            <a href="#" style="font-size: x-large"><li class="room-link" data-room-id="{{ room.id }}">{{ room }}</li></a>
            <span style="font-size: large">Current Leaderboard of this quiz:</span>
            <a href="{% url 'game:quiz_leaderboard' room.quiz.id %}" style="font-size:x-large">{{ Room }} leaderboard </a>
        {% empty %}
            <p class="empty">No chat rooms defined. Maybe make some in the <a href="{% url 'admin:index' %}">admin</a>?</p>
        {% endfor %}
        </div>
    {% else %}
        <a class="lead" href="{% url 'login' %}">Log in</a>
    {% endif %}
    </ol>

    <div id="chats">
    </div>
{% endblock %}
{% block extra_body %}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <script src="{% static "js/main.js" %}"></script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Profile{% endblock %}
{% block content %}

    {% if user.is_authenticated %}
        {% if scores %}
            <table border="3px">
            <tr align="center">
                <th>Quiz Name</th>
                <td>Maximum Score</td>
                <td>Score Obtained</td>
            </tr>
            {% for score in scores %}
                <tr align="center">
                <th>
                   <a href="{% url 'game:quiz_leaderboard' score.get_quiz_id %}">{{ score.get_quiz }}</a>
                </th>
                <td>
                    {{ score.get_max_score }}
                </td>
                <td>
                    {{ score.get_score }}
                </td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    {% else %}
        You aren't logged in.
    {% endif %}

{% endblock %}

templates/quiz/quiz_leaderboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}quizzie{% endblock %}
{% block content %}
    <h1>{{ quiz_name }}</h1>

    <br>
    <h2>Questions in quiz</h2>
    {% for question in questions %}
        <div>
            <h2>{{ question.question_text }}</h2>
            {% for choice in question.get_options %}
                <h3>{{ choice.text }}</h3>
            {% endfor %}
            <br>
            <br>
        </div>
    {% endfor %}
    <br>
    <br>
    <h1>LEADERBOARD</h1>
    <br>

    {% for score in scores %}
        <li><h3>{{ score }}</h3></li>
        <br>
    {% endfor %}

{% endblock %}
{% block extra_body %}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
{% endblock %}